# Generated by Django 5.0.3 on 2024-05-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blog.category'),
        ),
    ]
