# Generated by Django 5.0.3 on 2024-05-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_cate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cate',
            new_name='date',
        ),
    ]
